/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ggreen' at '1/14/17 9:42 AM' with Gradle 2.14.1
 *
 * @author ggreen, @date 1/14/17 9:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
